# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDRhNzY2OWU0NGU5M2M3ZjE4M2VlZjk3YjU3NGU3MGY3MDIyYzNmOWZhZGU5ODUwN2NkNGIzYTU5MDIyNzY2NDA3YmEyMWM4NGJhZDU2MTZlYTc5YjkzNjBkYjE3ODA3OTgxNGQzYTdlNGE4OTU0YjU0MmNjMGNiOTA1YzRlMjM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
